"""Helper template for Alembic migration scripts.
This is a minimal copy of the default template used by Alembic.
"""

"""
Revision ID: 3af71a55ae38
Revises: 
Create Date: 2025-12-01 04:57:45.470559
"""

# Alembic revision identifiers
revision = '3af71a55ae38'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_journal_entry_lines_account_code'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_opening_balances_account_code'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_ledger_entries_account_code'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_journal_entry_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('account_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('debit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('credit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ledger_entries_pkey'))
    )
    op.create_index(op.f('ix_ledger_entries_journal_entry_id'), 'ledger_entries', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_account_code'), 'ledger_entries', ['account_code'], unique=False)
    op.create_table('opening_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opening_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('opening_balances_pkey'))
    )
    op.create_index(op.f('ix_opening_balances_account_code'), 'opening_balances', ['account_code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'accountant', 'viewer', name='userrole'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_group', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('debit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('credit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('journal_entry_lines_journal_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entry_lines_pkey'))
    )
    op.create_index(op.f('ix_journal_entry_lines_account_code'), 'journal_entry_lines', ['account_code'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey'))
    )
    # ### end Alembic commands ###
